# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 720)
        self.lblCamara = QtWidgets.QLabel(Form)
        self.lblCamara.setGeometry(QtCore.QRect(40, 70, 600, 400))
        self.lblCamara.setAutoFillBackground(True)
        self.lblCamara.setText("")
        self.lblCamara.setObjectName("lblCamara")
        self.lblTitulo = QtWidgets.QLabel(Form)
        self.lblTitulo.setGeometry(QtCore.QRect(310, 10, 661, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.gbSec1 = QtWidgets.QGroupBox(Form)
        self.gbSec1.setGeometry(QtCore.QRect(40, 530, 311, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gbSec1.setFont(font)
        self.gbSec1.setObjectName("gbSec1")
        self.rbAprender = QtWidgets.QRadioButton(self.gbSec1)
        self.rbAprender.setGeometry(QtCore.QRect(20, 36, 131, 31))
        self.rbAprender.setChecked(True)
        self.rbAprender.setObjectName("rbAprender")
        self.rbAdivinar = QtWidgets.QRadioButton(self.gbSec1)
        self.rbAdivinar.setGeometry(QtCore.QRect(160, 40, 131, 31))
        self.rbAdivinar.setObjectName("rbAdivinar")
        self.btnIniciar = QtWidgets.QPushButton(self.gbSec1)
        self.btnIniciar.setGeometry(QtCore.QRect(0, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIniciar.setFont(font)
        self.btnIniciar.setObjectName("btnIniciar")
        self.gbSec2 = QtWidgets.QGroupBox(Form)
        self.gbSec2.setGeometry(QtCore.QRect(370, 530, 311, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gbSec2.setFont(font)
        self.gbSec2.setObjectName("gbSec2")
        self.lblResultadoA = QtWidgets.QLabel(self.gbSec2)
        self.lblResultadoA.setGeometry(QtCore.QRect(20, 60, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblResultadoA.setFont(font)
        self.lblResultadoA.setObjectName("lblResultadoA")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(680, 70, 501, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.rbInt1op1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbInt1op1.setGeometry(QtCore.QRect(20, 40, 171, 31))
        self.rbInt1op1.setObjectName("rbInt1op1")
        self.rbInt1op2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbInt1op2.setGeometry(QtCore.QRect(190, 40, 151, 31))
        self.rbInt1op2.setObjectName("rbInt1op2")
        self.rbInt1op3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbInt1op3.setGeometry(QtCore.QRect(350, 40, 151, 31))
        self.rbInt1op3.setObjectName("rbInt1op3")
        self.btnInt1 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnInt1.setGeometry(QtCore.QRect(130, 100, 241, 31))
        self.btnInt1.setObjectName("btnInt1")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(680, 220, 501, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.rbInt2op1 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbInt2op1.setGeometry(QtCore.QRect(20, 40, 171, 31))
        self.rbInt2op1.setObjectName("rbInt2op1")
        self.rbInt2op2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbInt2op2.setGeometry(QtCore.QRect(190, 40, 161, 31))
        self.rbInt2op2.setObjectName("rbInt2op2")
        self.rbInt2op3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbInt2op3.setGeometry(QtCore.QRect(350, 40, 151, 31))
        self.rbInt2op3.setObjectName("rbInt2op3")
        self.btnInt2 = QtWidgets.QPushButton(self.groupBox_4)
        self.btnInt2.setGeometry(QtCore.QRect(130, 100, 241, 31))
        self.btnInt2.setObjectName("btnInt2")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(680, 370, 501, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.rbInt3op1 = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbInt3op1.setGeometry(QtCore.QRect(20, 40, 171, 31))
        self.rbInt3op1.setObjectName("rbInt3op1")
        self.rbInt3op2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbInt3op2.setGeometry(QtCore.QRect(190, 40, 161, 31))
        self.rbInt3op2.setObjectName("rbInt3op2")
        self.rbInt3op3 = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbInt3op3.setGeometry(QtCore.QRect(350, 40, 151, 31))
        self.rbInt3op3.setObjectName("rbInt3op3")
        self.btnInt3 = QtWidgets.QPushButton(self.groupBox_5)
        self.btnInt3.setGeometry(QtCore.QRect(130, 90, 241, 31))
        self.btnInt3.setObjectName("btnInt3")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(700, 530, 481, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.lblResultadoB = QtWidgets.QLabel(self.groupBox_6)
        self.lblResultadoB.setGeometry(QtCore.QRect(20, 50, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblResultadoB.setFont(font)
        self.lblResultadoB.setObjectName("lblResultadoB")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DetectorFiguras v1.0"))
        self.lblTitulo.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#00557f;\">Aprender Figuras Geométricas Basicas</span></p></body></html>"))
        self.gbSec1.setTitle(_translate("Form", "Eligir que quieres hacer"))
        self.rbAprender.setText(_translate("Form", "Aprender"))
        self.rbAdivinar.setText(_translate("Form", "Adivinar"))
        self.btnIniciar.setText(_translate("Form", "INICIAR"))
        self.gbSec2.setTitle(_translate("Form", "Resultado Aprendizaje"))
        self.lblResultadoA.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">**********</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("Form", "Intento 1"))
        self.rbInt1op1.setText(_translate("Form", "Figura 1"))
        self.rbInt1op2.setText(_translate("Form", "Figura 2"))
        self.rbInt1op3.setText(_translate("Form", "Figura 3"))
        self.btnInt1.setText(_translate("Form", "Enviar"))
        self.groupBox_4.setTitle(_translate("Form", "Intento 2"))
        self.rbInt2op1.setText(_translate("Form", "Figura 1"))
        self.rbInt2op2.setText(_translate("Form", "Figura 2"))
        self.rbInt2op3.setText(_translate("Form", "Figura 3"))
        self.btnInt2.setText(_translate("Form", "Enviar"))
        self.groupBox_5.setTitle(_translate("Form", "Intento 3"))
        self.rbInt3op1.setText(_translate("Form", "Figura 1"))
        self.rbInt3op2.setText(_translate("Form", "Figura 2"))
        self.rbInt3op3.setText(_translate("Form", "Figura 3"))
        self.btnInt3.setText(_translate("Form", "Enviar"))
        self.groupBox_6.setTitle(_translate("Form", "Resultado Adivinar"))
        self.lblResultadoB.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">**********</span></p></body></html>"))

#import dir_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

